dist: trusty
sudo: false  # Use the new travis docker based infrastructure

git:
  # We need a deeper depth for 'git descibe' to ensure
  # we can reach the last tagged version.
  depth: 99999

language: python
matrix:
  include:
    - python: "3.5"
      env: CONDA_ENV_FILE=.travis/environment_py35.yaml
    - python: "2.7"
      env: CONDA_ENV_FILE=.travis/environment_py27.yaml

cache:
  directories:
    - $HOME/.cache/pip

# Install required packages
addons:
  postgresql: "9.5"
  services:
    - postgresql

before_install:
  # Create a database for the integration tests.
  - createdb agdcintegration

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -f -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  # travis specific goo
  - conda config --set always_yes yes --set changeps1 no
  - conda config --show-sources
  - conda config --show

  - conda config --prepend channels conda-forge
  - conda update --all

  # print conda info
  - conda info -a

  - conda env create -n agdc --file $CONDA_ENV_FILE
  - source activate agdc
  - pip install .[analytics,test,interactive] --no-deps --upgrade

  - pip freeze

script:
  - ./check-code.sh integration_tests

after_success:
  - coveralls

notifications:
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      secure: SCM9YZ215qZnDHHQrbgWQtaKa46ZgtsEbg8XPqdyhQdMnhXDQkNA8aJIFHaPNKs2MRfqXEz1dTigjAr7OlxlvENKdVXJDGvccaJlLWX6WckfkPinWE1nvEIR18MME4jEDp06jGww+eqBU0xniHGNa66EABiQml41XQTO3lHFzwAdx0uqG5o0irqkDGqeKW1QrZ++nUwx5W+0CJGNZO06yTIUQp6B8wfMnmaoVUUjw2xuQqUdub4TbnpGlj5T8yLbKayaMjlfGbznq7VcM+2hrT0vnKOZSu5qPBlmA7DYq9IGN3sFFa095WtRfstHGOWAHgDljgm0K/EJWAW7Pv7uAmx30I9RPA1sNq1ZxVJ4RwH5ZebRiaBVh43ik5l/vNrr4wZNLeRhgGUiCxEHrix5ZNahZAv/LDZrddRyspDLmgXsCb+ExPsHwamhieVAvjB24aDL8tj8Es1A75Ai1mtcCwuYGHQzeDAlTGP5XdJQWrpcySFkouMg85DPSNz++YSBzgNR+z7pPH7Hxc01ofplXB10AMMP0IgDyZNJ2JjqttDjrMKTrfXsakEb66mXBsJDg9qBPWV5R6GOcGVBMo1JnGWFoD9IGihTWdyxv7+TEZ/w+F8hyErqFzVkMwER/BwYiT/euIVIm/ZEgRpISwZmNWTg6tXo+M5WUZtQGGmAERI=
      secure: ADGOG3YqqYnLq2vT+3eIVr+Gr91Zp0+6n7V4C0hZziAf2wE6fKSqk9xamWad4a96c+kGnlK7xzUuqPretcfCY3ANFnZKtqyckBnMuU+wlUvCee9nybXmqXB+hfuNSVkeVkC51yVTzsnNhj5ASDy4OdD+duGUn9gY2fgHVf2WK8V98tFmt1kviV4h2me/d1+wNLu6hmtRWGW7klpY4Oz9pP6HruFvbTh28H2VArnpiT2t8PIEsNTIZNnOQOVUtUEdecB0svFRXKqCdklVns6wlyWsPpHWZ7HuxRy8K/wutKR85EFVxWiS9jCFSjPlzYBsyQyWq1oKiDVtusIha2XtsTMq1D+3wnPH1T8yFyqD4xuFCG0mkk99hGHlgCvYLDhzYLZdj2zcTewF3Oye3oxnoaeSRcsIS7i93Z9qxdWRIh093ZUr+rQ2hw6r2SSGBLaE+9pnlkVPU+JoeGHo9PsZzPKGMyUeSkQaLuBbTc4V308uAodPfJge0+BAz2TWe6w+bOrem+QaMtInGXcuAIWjQfFpxjOjBeegatobSitTvxPjeNgRrZTjPWEqAOgBEqcRcAymKP7bI8IOFSmH5KdLE6niB0yiatWOKQu8BVSRpZ4CiPK3MyVe09x0g5HCQJZ+bEjkDnCpkKtXTBuT9U8CHzTUqxfeZ3hiEOZFWPvVOyk=
