language: python

python:
  - "2.7"

# Use the new travis docker based infrastructure
sudo: false

# Install required packages
addons:
  postgresql: "9.4"
  apt:
    packages:
# libhdf4-alt-dev is not available on travis CI. It would appear this package is not required by tests at this time
# TODO: Check if this dependency is truly required
#    - libhdf4-alt-dev
    - libhdf5-serial-dev
    - libnetcdf-dev
    - libproj-dev
    - libgdal1-dev
# libgdal-dev has a packaging conflict on travis ci which causes it to uninstall postgis.
# TODO: Check if this dependency is truly required
#    - libgdal-dev

# Command to install miniconda to build test environment
before_install:
  # Python and packages
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      travis_retry wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Add Jess Robertson (CSIRO) binstar channel to get custom builds for some utilities
  - conda config --add channels jesserobertson
  - travis_retry conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create a database for the integration tests.
  - createdb agdcintegration

install:
  - conda create -q -n test-agdc python=$TRAVIS_PYTHON_VERSION nose pip sphinx numpy scipy matplotlib gdal netCDF4 numexpr psycopg2 coverage python-coveralls
  - source activate test-agdc
  - conda install -c http://conda.anaconda.org/jakirkham pylint
  - travis_retry pip install -r requirements.txt 
  - python setup.py install

script:
  - ./check-code.sh integration_tests

after_success:
  - coveralls
