name: lint


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop-1.9


concurrency:
  # Here the group is defined by the head_ref of the PR
  group: ${{ github.head_ref }}
  # Here we specify that we'll cancel any "in progress" workflow of the same group. Thus if we push, ammend a commit and push
  # again the previous workflow will be cancelled, thus saving us github action build minutes and avoid any conflicts
  cancel-in-progress: true


jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        lint-command:
          - "pylint --j 2 --reports no datacube"
          - "--group types mypy datacube"
          - "pycodestyle tests integration_tests examples --max-line-length 120"

    name: Code Lint
    steps:
      - name: checkout git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: 0.5.5
          enable-cache: 'true'
          cache-suffix: ${{ matrix.python-version }}
      - name: Run ${{ matrix.lint-command }}
        run: |
          uv run ${{ matrix.lint-command }}
