name: lint

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/lint.yaml'
      - '!docker/**'
      - '!docs/**'
      - '!contrib/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        lint-command:
          - "pylint --j 2 --reports no datacube"
          - "--group types mypy datacube"
          - "pycodestyle tests integration_tests examples --max-line-length 120"

    name: Code Lint
    steps:
      - name: checkout git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: 0.5.5
          enable-cache: 'true'
          cache-suffix: ${{ matrix.python-version }}
      - name: Run ${{ matrix.lint-command }}
        run: |
          uv run ${{ matrix.lint-command }}

