name: lint

on:
  pull_request:
    paths:
      - '**'

  push:
    branches:
      - develop
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/lint.yaml'
      - '!docker/**'
      - '!docs/**'
      - '!contrib/**'
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        lintcommand:
          - "pylint -j 2 --report no datacube"
          - "mypy datacube"
          - "pycodestyle tests integration_tests examples --max-line-length 120"
    name: Linting
    steps:
      - name: checkout git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: run linter
        with:
          persist-credentials: false
        run: |
          uv run --no-project --with '.[test,types]' ${LINT_COMMAND}
        env:
          LINT_COMMAND: ${{matrix.lintcommand}}
          UV_PYTHON: ${{ matrix.python-version }}
          UV_PYTHON_PREFERENCE: managed
