name: Conda Smoke Test
on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'

jobs:
  check-conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Cache conda
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if setup.py has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: conda-environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version}}

      - name: Bash
        shell: bash -l {0}
        run: |
          pip install .
          python --version
          datacube --version
          conda env export
